// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Activity {
    activityCategoryName: string;
    activityDisplayName:  string;
    activityGroupId:      number;
    activityGroupName:    string;
    activityId:           number;
    activityName:         string;
    bookingId:            null;
    bookingInformation:   null;
    brand:                string;
    center:               Center;
    collapseKey:          string;
    comment:              null;
    commentCount:         number;
    date:                 string;
    distance:             number;
    duration:             number;
    endTime:              string;
    eventStatus:          string;
    eventType:            string;
    externalMemberId:     string;
    followingBookings:    FollowingBooking[];
    groupExerciseTypeId:  string;
    id:                   string;
    imageUrl:             string;
    imageUrlCdn:          string;
    instructor:           string;
    instructorId:         null;
    isPrivate:            boolean;
    location:             null;
    member:               Member;
    memberId:             string;
    participationId:      string;
    reactions:            any[];
    source:               string;
    startTime:            string;
    timestamps:           Timestamps;
}

export interface Center {
    country:           string;
    id:                number;
    isCorporateCenter: boolean;
    name:              string;
}

export interface FollowingBooking {
    commentCount:     number;
    country:          string;
    eventData:        EventData;
    eventId:          string;
    externalMemberId: string;
    firstName:        string;
    fullName:         string;
    gender:           string;
    lastName:         string;
    memberId:         string;
    photo:            null;
    reactions:        any[];
    satsId:           null;
    status:           string;
}

export interface EventData {
    activityDisplayName: string;
    center:              Center;
    comment:             null;
    date:                string;
    distance:            number;
    duration:            number;
    endTime:             string;
    image:               string;
    instructor:          string;
    startTime:           string;
}

export interface Member {
    bookingState:        null;
    participationId:     null;
    waitingListPosition: number;
}

export interface Timestamps {
    created: string;
    updated: string;
}
