import { StravaSportType } from "./strava";

export type StravaCreateActivity = {
    name: string;
    sport_type: StravaSportType;
    start_date_local: string;
    elapsed_time: number;
    description: string;
    distance: number;
    trainer: number;
    commute: number;
};

// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface StravaActivity {
    id:                   number;
    resource_state:       number;
    external_id:          null;
    upload_id:            null;
    athlete:              Athlete;
    name:                 string;
    distance:             number;
    moving_time:          number;
    elapsed_time:         number;
    total_elevation_gain: number;
    type:                 string;
    sport_type:           string;
    start_date:           string;
    start_date_local:     string;
    timezone:             string;
    utc_offset:           number;
    achievement_count:    number;
    kudos_count:          number;
    comment_count:        number;
    athlete_count:        number;
    photo_count:          number;
    map:                  Map;
    trainer:              boolean;
    commute:              boolean;
    manual:               boolean;
    private:              boolean;
    flagged:              boolean;
    gear_id:              string;
    from_accepted_tag:    null;
    average_speed:        number;
    max_speed:            number;
    device_watts:         boolean;
    has_heartrate:        boolean;
    pr_count:             number;
    total_photo_count:    number;
    has_kudoed:           boolean;
    workout_type:         null;
    description:          null;
    calories:             number;
    segment_efforts:      any[];
}

export interface Athlete {
    id:             number;
    resource_state: number;
}

export interface Map {
    id:             string;
    polyline:       null;
    resource_state: number;
}
